name: deploy-auth

on:
  push:
    branches: 
      - master
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/auth && docker build -t hoanghiep2004hy/auth .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hoanghiep2004hy/auth
