apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: hoanghiep2004hy/auth
          context: auth
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.ts'
                  dest: .
        - image: hoanghiep2004hy/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '**/*.ts'
                  dest: .
        - image: hoanghiep2004hy/tickets
          context: tickets
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.ts'
                  dest: .
        - image: hoanghiep2004hy/orders
          context: orders
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.ts'
                  dest: .
        - image: hoanghiep2004hy/expiration
          context: expiration
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.ts'
                  dest: .