name: deploy-manifest

on:
  push:
    branches: 
      - master
    paths:
      - 'ticketing/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to Linode k8s
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ticketing/infra/k8s
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ticketing/infra/k8s-prod
